name: r-type workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - server
      - client
      - yma/release_automation # test
  pull_request:

env:
  EXECUTABLES:  r-type_client, r-type_server

jobs:
  check_program_compilation:
    name: Check compilation
    runs-on: ubuntu-latest
    container:
      image: mathieubrl/rtype
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/
          key: ${{ hashFiles('vcpkg.json') }}

      - name: Setup vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
          fi
          ./vcpkg/vcpkg install

      - name: Compilation
        run: |
          ./release.sh

      - name: Verify if files exist and are executable
        run: |
          for exe in $(echo $EXECUTABLES | tr ',' ' ');
            do
            if [ ! -x $exe ]; then exit 1; fi;
            done;
          exit 0;

  build_and_deploy:
    if: github.ref == 'refs/heads/yma/release_automation'
    needs: check_program_compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.27.4'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ='Europe/Paris' date +'%Y.%m.%d.%H.%M')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: r-type_executables
          path: |
            ./r-type_client
            ./r-type_server
